version: '3'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/home/www/code
    working_dir: /home/www/code
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./src:/home/www/code
    ports:
      - 80:80
    depends_on:
      - php